### PR TITLE
anvil-gen: advance dependency management and fix code generation for …

### PR DESCRIPTION
**Pull request by tilal6991**
…strange classes

The first thing this commit does is increase the flexibility of
dependencies - it means that libraries can have multiple jars of the
same project that they depend on. AppCompat is updated to make use of
this by referring to the internal library jar of support v4.

Next, this commit moves from using Java style get{Blah} calls when
working with classes to {blah} parameter accesses during code
generation. Now this may seem like a style change but for some black
magic reason, the former tries to instantiate the class and the latter
doesn't!!! This is even though both should just call the get{Blah}
function. I'm not sure why this happens - if someone else who is more
knowledgable on Groovy sees this please let me know!

This commit also allows enforces that all methods considered have public
method parameters so a compile error would not be caused when invoking
the method outside the package - this removes the need for manual quirks
for these sorts of classes.

Finally, this commit regenerates the appcompat-v7 library DSL adding a
bunch of new methods which was possible using all of the above :)

### CODE REVIEW

**Comment by tilal6991** [comment]
There seems to be a lot in this commit but the pieces go well together. They also lay the foundation for support-v4.

**Comment by zserge** [comment]
Amazing! I still can't believe that support libraries are finally coming to Anvil as first class citizens.
On a side note, I would consider SDK15 as the minimal supported version because for the next Anvil release I would prefer to abandon SDK10 support and bring support for SDK21 instead. I'm not calling to change everything to SDK15, just if you need something that is missing in SDK10 - don't hesitate to increase the minimal API level. Looking at the statistics of the Play Store I don't see any 2.3.3 devices in the lists for the new apps, however some people may prefer to have a native material design still covering almost half of the devices.

**Comment by zserge** [comment]
Also, if you're making some quick test apps to validate the generated bindings - feel free to add them to anvil-examples repository.

**Comment by tilal6991** [comment]
Yup totally get dropping API 10 if necessary. I just made min 10 because I could - I would have no problem with them being bumped.

Yeah I'm glad I discovered Anvil/Redux - really opened my mind to how the power of FP can me brought to the JVM. 

As for test apps - I can write a couple sure. Publishing the support library artefacts would make that easier :)

**Pull request merged**
