### PR TITLE
A better approach for handling attributes and views.

### LINKED ISSUE #83: Anvil.currentView() is null inside render method
Any ideas why the following exception is being thrown by withId()?

```
Caused by: java.lang.RuntimeException: Anvil.currentView() is null
at trikita.anvil.BaseDSL.withId(BaseDSL.java:688)
```

The issue occurs in the render cycle immediately after the view in question is removed from its parent, like this:

Pass 1:

```
linearLayout(() -> {
    v(SomeView.class, () -> {});
    v(SomeView.class, () -> {});
    v(SomeView.class, () -> {});
}) 
```

Pass 2:

```
linearLayout(() -> {
    v(SomeView.class, () -> {});
    // Removed
    v(SomeView.class, () -> {});
}) 
```

SomeView's render method where the crash is thrown is essentially this:

```
@Override
public void view() {
    xml(R.layout.some_view, () -> {
        // Crash here
        withId(R.id.button, () -> {
        }
    }
```

### PR DESCRIPTION
**Pull request by zserge**
This is what is likely to become Anvil 0.5.0 soon :tada: 

Major changes:

* Removed `Anvil.Node` class, using views directly. This should resolve #83 and maybe other issues related to missynchronization between virtual view nodes and real views. In fact, working with views directly happens at the same speed as dealing with virtual nodes (unlike DOM vs virtual DOM in the web).
* Replaced hundreds of lambdas in DSL classes with a single switch/case per class. This reduces number of methods (each lambda has 2 methods - a contstructor and an actual method, so we had ~2k methods in DSL.java, now we have ~500).
* This allows to set attribute by its string name, so I've added a last-resort attribute handler which uses reflection (a-la android Property class). So if your attribute is missing in DSL - just use `attr("foo", someValue)`. It won't be fast, but works fine for one-time constant values.
* This in its turn opens the doors to reusable components. If a component (a RenderableView) has custom setters - one can use them using their string names.
* Alternatively, one may register his own attribute handler to get rid of reflection. Multiple attribute handlers are chained, reflection-based is the last one, common DSL goes next, then support DSLs, then your own ones.
* As a bonus this also resolves issues with the attributes of the same name (e.g. `gravity` in DSL and `gravity` in support DSL). Now such name clashes just work as expected.

Benchmarks show that is gives a slight performance gain (~5%) comparing to Anvil 0.5.0, but the main code part becomes much simpler and the flexibility is extremely high, so I'm merging this into master branch.

### CODE REVIEW

**Comment by gmarques33** [comment]
Hi,
do you plan to release the actual master as Anvil 0.5.0 or are you planning major changes?

Btw, great work 👍

**Comment by zserge** [comment]
@gmarques33 Anvil 0.5.0 is planned to be released this week, and good news is that the public API is backwards-compatible with Anvil 0.4.0. Although, internally lots of things have changed, and new added APIs such as custom attribute factories or view factories or `Anvil.skip()` might not be final yet.

**Comment by gmarques33** [comment]
@zserge Cool. I look forward to trying the new changes. We are testing it in a project and I believe that 0.5.0 changes will help a lot.
If we keep using it, we can contribute with feedback and pull requests 👍

**Comment by Jakst** [comment]
I'm trying to use the bottomNavigationView introduced in this merge, but simply cannot get it to trigger my NavigationItemSelectedListener. Is this functionality not complete? The documentation on such components is currently non-existent.

```kotlin
class HomeView(c: Context) : RenderableView(c) {

    private val mOnNavigationItemSelectedListener = BottomNavigationView.OnNavigationItemSelectedListener { item ->
        when (item.itemId) {
            R.id.navigation_home -> {
                println("HOME")
                return@OnNavigationItemSelectedListener true
            }
            R.id.navigation_dashboard -> {
                println("Dash")
                return@OnNavigationItemSelectedListener true
            }
            R.id.navigation_notifications -> {
                println("Notif")
                return@OnNavigationItemSelectedListener true
            }
        }
        false
    }

    override fun view() {
        frameLayout {
            size(BaseDSL.MATCH, BaseDSL.MATCH)

            bottomNavigationView {
                gravity(BaseDSL.BOTTOM)
                size(BaseDSL.MATCH, BaseDSL.WRAP)
                onNavigationItemSelected(mOnNavigationItemSelectedListener)

                bottomNavigationMenuView {
                    bottomNavigationItemView {
                        title("Home")
                        id(R.id.navigation_home)
                        icon(ContextCompat.getDrawable(context, R.drawable.ic_home_black_24dp))
                    }
                    bottomNavigationItemView {
                        title("Dash")
                        id(R.id.navigation_dashboard)
                        icon(ContextCompat.getDrawable(context, R.drawable.ic_home_black_24dp))
                    }
                    bottomNavigationItemView {
                        title("Notif")
                        id(R.id.navigation_notifications)
                        icon(ContextCompat.getDrawable(context, R.drawable.ic_home_black_24dp))
                    }
                }
            }
        }
    }
}
```

**Comment by zserge** [comment]
@Jakst Yes, it's another gift from Android Support Library developers, similar to #81 and friends.

Basically, they are violating the common convention of the view constructors. BottomNavigationView is a view group, but it injects child views automatically, as well as having other side effects such as binding together the menu presented and menu view. In other words, you can't create a BottomNavigationView in pure java without using XMLs.

Here's where the child view is added: https://android.googlesource.com/platform/frameworks/support/+/master/design/src/android/support/design/widget/BottomNavigationView.java#171

But this particular case is not so bar. One can specify the Menu resource in code, so I've been using the following view method in my component and it worked well:

```java
        public void view() {
            frameLayout(() -> {
                size(MATCH, MATCH);

                bottomNavigationView(() ->  {
                    init(() -> {
                        ((BottomNavigationView) Anvil.currentView()).inflateMenu(R.menu.bottom_nav_example);
                    });

                    gravity(BOTTOM);
                    size(MATCH, WRAP);
                    onNavigationItemSelected(mOnNavigationItemSelectedListener);
                });
            });
        }
```

Here I'm creating a view in java, but my menu items are declared in menu XML, much like the documentation suggests. Not as good as pure Kotlin (or Java), but it seems to be the only possible way. An alternative would be to re-write BottomNavigationView as your own class that would be Java- (and thus, Anvil-) friendly.

**Comment by zserge** [comment]
@Jakst You might want to open a separate issue if you would prefer to have a separate method like `menu(int resource)` instead of the `init(...) + inflateMenu` trick. A solution would be to modify quirks file and re-generate the DSL code, so you might want to offer a pull request to make it faster.

**Pull request merged**
